source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'Example' do
  platform :ios, '12.0'

  pod 'BRBankSlipChecker', :path => '../'

  target 'Tests' do
    inherit! :search_paths
  end
end
